sonar.projectKey=UserManagementApi
sonar.projectName=User Management API
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**,**/publish/**

sonar.cs.vstest.reportsPaths=TestResults/**/*.trx
sonar.cs.cobertura.reportsPaths=TestResults/**/coverage.cobertura.xml
